### ISSUE TITLE
Unable to start/stop/restart mysqld

### ISSUE THREAD

**Issue by whylom** [cookbooks/mysql#1]
The server recipe appears to work perfectly when I use it to install MySQL on a Vagrant virtual machine.  But I am unable to start, stop, or restart the mysqld process by any of the means I normally use.

All of these commands:

```
/etc/init.d/mysql restart
service mysql restart
restart mysql
```

result in this error message:

```
restart: Unable to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
```

Am I doing something wrong? Please let me know if I can provide more information.

**Comment by whylom** [comment]
I just figured it out - I wasn't running the commands with sudo.  Sorry to trouble you, and thanks for this excellent cookbook!

**Comment by aboehrnsen** [comment]
thanks for the advice. I had the same problem :)

**Comment by robwilkerson** [comment]
I'm having the same problem, but at least in my case, it's preventing the provisioning from completing. Even if I login and attempt to manually run `sudo service mysql start`, I get nothing.

**Comment by aboehrnsen** [comment]
Rob, you can try running it manually by executing

```
 /usr/sbin/mysqld
```

Then you will see debug output.
Running it with 

```
service mysql start
```

Will not give you that (immediately)

**Comment by robwilkerson** [comment]
@aboehrnsen - I've changed things up a bit, so I can't do that right now, but what I ultimately got in my `/var/log/syslog` and through `dmesg` was this:

```
init: mysql respawning too fast, stopped
```
